In [1]:
import numpy as np

### Exercise 1

Generate an array that goes from 20 to 60.

#### Solution

In [2]:
arr_ej1 = np.arange(20, 60+1)
arr_ej1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

### Exercise 2

Of the previous array show the array from start to end, by 5 elements

#### Solution

In [3]:
arr_ej1[:: 5]

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

### Exercise 3

Take as reference the array of the exercise 1 and, show from the element 30 to the and by 2 elements

#### Solution

In [4]:
arr_ej1[10 :: 2]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

### Exercise 4

Take as reference the array of the exercise 1 and, show the array from position -10 to the begging by -2 steps

#### Solution

In [5]:
arr_ej1[-10::-2]

array([51, 49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21])

### Exercise 5

Create a regular matrix (a regular matrix has the same number of rows than columns) with the elements from 1 to 9

#### Solution

In [6]:
vec = np.arange(1, 10) # From 1 to 9

In [7]:
mat_reg = vec.reshape(3,3) # Reshape the vector into 3x3

In [8]:
mat_reg

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 6

Take the following array

In [9]:
ej_6 = np.array([
    [10, 30, 45, 150],
    [12, 40, 20, 10]
])

ej_6


array([[ 10,  30,  45, 150],
       [ 12,  40,  20,  10]])

Create a flat array and then, show all the elements except the first and last

#### Solution

In [10]:
flat_ej6 = ej_6.flatten()

In [11]:
flat_ej6[(flat_ej6 != 10)]

array([ 30,  45, 150,  12,  40,  20])

In [12]:
# Different solution with index

In [13]:
flat_ej6[1 : -1]

array([ 30,  45, 150,  12,  40,  20])

### Exercise 7

Create a matrix of 3x3 with all the elements from 100 to 112 (if it's possible)

#### Solution

In [14]:
arr_ej7 = np.arange(100,112).reshape((3, 4))
arr_ej7

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [15]:
# You can't generate from exactly to 12 because it's not divisible by 13 elements

### Exercise 8

From the previous array, show only the values higher than 106, in wich format the values are returned ?

#### Solution

In [16]:
arr_ej7[(arr_ej7 > 106)] # flat array

array([107, 108, 109, 110, 111])

### Exercise 9

Take the following arrays 

In [17]:
one = np.arange(0, 6).reshape(2,3)
two = np.arange(6, 12).reshape(2,3)

Join both arrays so that you get an array with a `shape(2,6)` structure, finally show its transpose

#### Solution

In [18]:
type_one = np.concatenate((one, two), axis=1)
type_one

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [19]:
type_one.shape

(2, 6)

In [20]:
type_one.T

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [21]:
type_two = np.hstack((one, two))
type_two

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [22]:
type_two.shape

(2, 6)

In [23]:
type_two.T

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [ 6,  9],
       [ 7, 10],
       [ 8, 11]])

### Exercise 10

Write a program that generates a 10x10 matrix with edge elements 1 and interior elements 0.

#### Solution

In [24]:
ones_zeros = np.ones(100).reshape(10, 10)
ones_zeros

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
ones_zeros[1: -1, 1: -1] = 0

In [26]:
ones_zeros

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
# You can check what we are indexing
ones_zeros[1: -1, 1: -1]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### Exercise 11

Normalize all the elements of the array, following the Z-Score formula https://www.statisticshowto.com/probability-and-statistics/z-score/

#### Solution

In [28]:
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

In [29]:
z_score = (aux - np.mean(aux)) / (np.std(aux))
z_score

array([[-0.48517794,  2.2336494 , -0.37532633],
       [-0.45771504, -0.40278924, -0.51264085]])

### Exercise 12

Normalize all the elements of the array, following the Min-Max formula https://en.wikipedia.org/wiki/Feature_scaling

#### Solution

In [30]:
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

In [31]:
(aux - np.min(aux)) / (np.max(aux) - np.min(aux))

array([[0.01, 1.  , 0.05],
       [0.02, 0.04, 0.  ]])

### Exercise 13

Write the following arrays:
* 10 zeros
* 10 ones
* 10 sevens

#### Solution

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones(10)*7

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])