# Exercise 1

In [1]:
import numpy as np

In [2]:
bananas = np.array([5, 8, 12, 6, 9, 4, 7])

In [3]:
apples = np.array([32, 25, 15, 36, 45, 22, 17])

In [4]:
oranges = np.array([16, 14, 15, 20, 21, 25, 10])

In [5]:
# First create the table with all the quantities
products_sold = np.concatenate([bananas, apples, oranges], 0).reshape(3, 7).T
products_sold

array([[ 5, 32, 16],
       [ 8, 25, 14],
       [12, 15, 15],
       [ 6, 36, 20],
       [ 9, 45, 21],
       [ 4, 22, 25],
       [ 7, 17, 10]])

In [6]:
# Create the table prices
prices = np.array([5, 3, 2])
prices

array([5, 3, 2])

In [7]:
total_amount = prices.dot(products_sold.T)

In [8]:
# Total amount by day
total_amount

array([153, 143, 135, 178, 222, 136, 106])

In [9]:
# We can check that (5*5 + 32*2 + 16*2) = 153

Total of benefits

In [10]:
total_amount.sum()

1073

Now, we are going to get the total amount by product

In [11]:
np.array(np.split(prices, 3))

array([[5],
       [3],
       [2]])

In [12]:
total_beneficts_day = np.array(np.split(prices, 3))*(products_sold.T)

In [13]:
total_beneficts_day.sum(axis=1)

array([255, 576, 242])

Get the mean of units sold by vegetable.

In [14]:
products_sold.mean(0)

array([ 7.28571429, 27.42857143, 17.28571429])

In [15]:
print("Mean of units sold of Bananas ", round(products_sold.mean(0)[0], 2))

Mean of units sold of Bananas  7.29


Get the mean of units sold by day.

In [16]:
products_sold.mean(1)

array([17.66666667, 15.66666667, 14.        , 20.66666667, 25.        ,
       17.        , 11.33333333])

In [17]:
print("Mean of units sold in Monday ", round(products_sold.mean(1)[0], 2))

Mean of units sold in Monday  17.67


# Exercise 2

In [18]:
first_row = np.array([6, 55, 12, 32, 20, 15])
second_row = np.array(first_row) *2
third_row = np.array(second_row) -5 
fourth_row = np.array(third_row)**2

matrix = np.array([
    first_row,
    second_row,
    third_row,
    fourth_row
])

matrix

array([[    6,    55,    12,    32,    20,    15],
       [   12,   110,    24,    64,    40,    30],
       [    7,   105,    19,    59,    35,    25],
       [   49, 11025,   361,  3481,  1225,   625]])

In [19]:
# odd
matrix[(matrix % 2 != 0)]

array([   55,    15,     7,   105,    19,    59,    35,    25,    49,
       11025,   361,  3481,  1225,   625])

In [20]:
# pairs
matrix[(matrix % 2 != 1)]

array([  6,  12,  32,  20,  12, 110,  24,  64,  40,  30])

# Exercise 3

In [21]:
a = np.array([
    [1, -7, -1],
    [2, +1, +6],
    [-1, +2, -1]
])

# Independent term
b = np.array([5, 12, 6])

In [22]:
print("X, Y, Z values ",np.linalg.solve(a, b))

X, Y, Z values  [-41.9  -9.2  17.5]


# Exercise 4

* Create a 1-dimensional NumPy array using np.array(), check the number of dimensions with ndim
* Create a 2-dimensional NumPy array using np.array(), check the number of dimensions with ndim
* Create a 3-dimensional Numpy array using np.array(), check the number of dimensions with ndim
* Create an array of shape (7, 2, 3) of only zeros
* Create an array within a range of 0 and 100 with step 3
* Explore the random functions and create the following arrays
    * Create a random array with numbers between 0 and 10 of size (7, 2)
    * Create an array of normally distributed random numbers
    * Create an array of 20 numbers of a Beta distribution with parameters 0.2 and 0.5
    * Create an array of 100 numbers of a Binomial distribution with parameters 0.5
    * Create a matrix of 3x3x3 with np.random.random


In [23]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

In [24]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
                [4, 5, 6]])

In [25]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [26]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [27]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[3, 0],
       [1, 4],
       [8, 0],
       [0, 6],
       [5, 1],
       [9, 1],
       [2, 1]])

* Create an array of normally distributed random numbers

In [30]:
randn = np.random.randn(10)
randn

array([-0.63284264, -0.76196784, -0.31878191,  1.00623134,  1.53690719,
        0.04805985,  0.59696144, -1.20840928, -0.02927078,  1.25862589])

* Create an array of 20 numbers of a Beta distribution with parameters 0.2 and 0.5

In [31]:
beta = np.random.beta(0.2, 0.5, 10)
beta

array([3.82565828e-01, 8.39233081e-01, 7.99313294e-05, 2.22094696e-05,
       7.79318878e-02, 4.70739154e-01, 6.92380843e-01, 4.82461989e-03,
       9.65573601e-01, 8.62239975e-01])

* Create an array of 100 numbers of a Binomial distribution with parameters 0.5

In [32]:
binomial = np.random.binomial(10, 0.5, 10)
binomial

array([7, 5, 3, 2, 6, 4, 7, 3, 6, 7])

* Create a matrix of 3x3x3 with np.random.random

In [33]:
my_array = np.random.random((3, 3, 3))
my_array

array([[[0.83073563, 0.42216839, 0.4868621 ],
        [0.38492324, 0.99150963, 0.32047702],
        [0.79406645, 0.94526644, 0.09129541]],

       [[0.31040846, 0.78354095, 0.2628364 ],
        [0.09916233, 0.86987625, 0.18779829],
        [0.22480746, 0.42461208, 0.57231564]],

       [[0.63155714, 0.52369113, 0.46405666],
        [0.63110295, 0.24722268, 0.15990769],
        [0.12368651, 0.0351228 , 0.32815309]]])